import { SoccerBotCountry } from './interfaces';

export const TRANSFERMARKT_COUNTRY: { [key: number]: SoccerBotCountry } = {
  1: SoccerBotCountry.AFGHANISTAN,
  3: SoccerBotCountry.ALBANIA,
  4: SoccerBotCountry.ALGERIA,
  239: SoccerBotCountry.AMERICAN_SAMOA,
  234: SoccerBotCountry.US_VIRGIN_ISLANDS,
  5: SoccerBotCountry.ANDORRA,
  6: SoccerBotCountry.ANGOLA,
  232: SoccerBotCountry.ANGUILLA,
  7: SoccerBotCountry.ANTIGUA_AND_BARBUDA,
  9: SoccerBotCountry.ARGENTINA,
  10: SoccerBotCountry.ARMENIA,
  233: SoccerBotCountry.ARUBA,
  12: SoccerBotCountry.AUSTRALIA,
  127: SoccerBotCountry.AUSTRIA,
  13: SoccerBotCountry.AZERBAIJAN,
  14: SoccerBotCountry.BAHAMAS,
  15: SoccerBotCountry.BAHRAIN,
  16: SoccerBotCountry.BANGLADESH,
  17: SoccerBotCountry.BARBADOS,
  18: SoccerBotCountry.BELARUS,
  19: SoccerBotCountry.BELGIUM,
  20: SoccerBotCountry.BELIZE,
  21: SoccerBotCountry.BENIN,
  211: SoccerBotCountry.BERMUDA,
  22: SoccerBotCountry.BHUTAN,
  23: SoccerBotCountry.BOLIVIA,
  269: SoccerBotCountry.BONAIRE,
  24: SoccerBotCountry.BOSNIA_AND_HERZEGOVINA,
  25: SoccerBotCountry.BOTSWANA,
  26: SoccerBotCountry.BRAZIL,
  231: SoccerBotCountry.BRITISH_VIRGIN_ISLANDS,
  27: SoccerBotCountry.BRUNEI,
  28: SoccerBotCountry.BULGARIA,
  29: SoccerBotCountry.BURKINA_FASO,
  30: SoccerBotCountry.BURUNDI,
  79: SoccerBotCountry.CAMBODIA,
  31: SoccerBotCountry.CAMEROON,
  80: SoccerBotCountry.CANADA,
  32: SoccerBotCountry.CAPE_VERDE,
  229: SoccerBotCountry.CAYMAN_ISLANDS,
  138: SoccerBotCountry.CENTRAL_AFRICAN_REPUBLIC,
  171: SoccerBotCountry.CHAD,
  33: SoccerBotCountry.CHILE,
  34: SoccerBotCountry.CHINA,
  164: SoccerBotCountry.CHINESE_TAIPEI,
  83: SoccerBotCountry.COLOMBIA,
  35: SoccerBotCountry.COMOROS,
  85: SoccerBotCountry.CONGO,
  238: SoccerBotCountry.COOK_ISLANDS,
  36: SoccerBotCountry.COSTA_RICA,
  38: SoccerBotCountry.IVORY_COAST,
  37: SoccerBotCountry.CROATIA,
  88: SoccerBotCountry.CUBA,
  260: SoccerBotCountry.CURACAO,
  188: SoccerBotCountry.CYPRUS,
  172: SoccerBotCountry.CZECH_REPUBLIC,
  39: SoccerBotCountry.DENMARK,
  41: SoccerBotCountry.DJIBOUTI,
  42: SoccerBotCountry.DOMINICA,
  43: SoccerBotCountry.DOMINICAN_REPUBLIC,
  193: SoccerBotCountry.DR_CONGO,
  44: SoccerBotCountry.ECUADOR,
  2: SoccerBotCountry.EGYPT,
  45: SoccerBotCountry.EL_SALVADOR,
  189: SoccerBotCountry.ENGLAND,
  8: SoccerBotCountry.EQUATORIAL_GUINEA,
  46: SoccerBotCountry.ERITREA,
  47: SoccerBotCountry.ESTONIA,
  162: SoccerBotCountry.ESWATINI,
  11: SoccerBotCountry.ETHIOPIA,
  208: SoccerBotCountry.FAROE_ISLANDS,
  111: SoccerBotCountry.MICRONESIA,
  48: SoccerBotCountry.FIJI,
  49: SoccerBotCountry.FINLAND,
  50: SoccerBotCountry.FRANCE,
  252: SoccerBotCountry.FRENCH_GUIANA,
  51: SoccerBotCountry.GABON,
  53: SoccerBotCountry.GEORGIA,
  40: SoccerBotCountry.GERMANY,
  54: SoccerBotCountry.GHANA,
  266: SoccerBotCountry.GIBRALTAR,
  56: SoccerBotCountry.GREECE,
  55: SoccerBotCountry.GRENADA,
  251: SoccerBotCountry.GUADELOUPE,
  241: SoccerBotCountry.GUAM,
  58: SoccerBotCountry.GUATEMALA,
  59: SoccerBotCountry.GUINEA,
  60: SoccerBotCountry.GUINEA_BISSAU,
  61: SoccerBotCountry.GUYANA,
  62: SoccerBotCountry.HAITI,
  66: SoccerBotCountry.HONDURAS,
  218: SoccerBotCountry.HONG_KONG,
  178: SoccerBotCountry.HUNGARY,
  73: SoccerBotCountry.ICELAND,
  67: SoccerBotCountry.INDIA,
  68: SoccerBotCountry.INDONESIA,
  71: SoccerBotCountry.IRAN,
  70: SoccerBotCountry.IRAQ,
  72: SoccerBotCountry.IRELAND,
  74: SoccerBotCountry.ISRAEL,
  75: SoccerBotCountry.ITALY,
  76: SoccerBotCountry.JAMAICA,
  77: SoccerBotCountry.JAPAN,
  78: SoccerBotCountry.JORDAN,
  81: SoccerBotCountry.KAZAKHSTAN,
  82: SoccerBotCountry.KENYA,
  246: SoccerBotCountry.KIRIBATI,
  86: SoccerBotCountry.NORTH_KOREA,
  87: SoccerBotCountry.SOUTH_KOREA,
  244: SoccerBotCountry.KOSOVO,
  89: SoccerBotCountry.KUWAIT,
  90: SoccerBotCountry.KYRGYZSTAN,
  91: SoccerBotCountry.LAOS,
  92: SoccerBotCountry.LATVIA,
  94: SoccerBotCountry.LEBANON,
  93: SoccerBotCountry.LESOTHO,
  95: SoccerBotCountry.LIBERIA,
  96: SoccerBotCountry.LIBYA,
  97: SoccerBotCountry.LIECHTENSTEIN,
  98: SoccerBotCountry.LITHUANIA,
  99: SoccerBotCountry.LUXEMBOURG,
  219: SoccerBotCountry.MACAU,
  100: SoccerBotCountry.MACEDONIA,
  101: SoccerBotCountry.MADAGASCAR,
  102: SoccerBotCountry.MALAWI,
  103: SoccerBotCountry.MALAYSIA,
  104: SoccerBotCountry.MALDIVES,
  105: SoccerBotCountry.MALI,
  106: SoccerBotCountry.MALTA,
  268: SoccerBotCountry.NORTHERN_MARIANA_ISLANDS,
  207: SoccerBotCountry.MARTINIQUE,
  108: SoccerBotCountry.MAURITANIA,
  109: SoccerBotCountry.MAURITIUS,
  110: SoccerBotCountry.MEXICO,
  112: SoccerBotCountry.MOLDOVA,
  114: SoccerBotCountry.MONGOLIA,
  216: SoccerBotCountry.MONTENEGRO,
  235: SoccerBotCountry.MONTSERRAT,
  107: SoccerBotCountry.MOROCCO,
  115: SoccerBotCountry.MOZAMBIQUE,
  116: SoccerBotCountry.MYANMAR,
  117: SoccerBotCountry.NAMIBIA,
  118: SoccerBotCountry.NAURU,
  119: SoccerBotCountry.NEPAL,
  122: SoccerBotCountry.NETHERLANDS,
  236: SoccerBotCountry.NEW_CALEDONIA,
  120: SoccerBotCountry.NEW_ZEALAND,
  121: SoccerBotCountry.NICARAGUA,
  123: SoccerBotCountry.NIGER,
  124: SoccerBotCountry.NIGERIA,
  261: SoccerBotCountry.NIUE,
  192: SoccerBotCountry.NORTHERN_IRELAND,
  125: SoccerBotCountry.NORWAY,
  126: SoccerBotCountry.OMAN,
  242: SoccerBotCountry.TIMOR_LESTE,
  128: SoccerBotCountry.PAKISTAN,
  240: SoccerBotCountry.PALESTINE,
  129: SoccerBotCountry.PALAU,
  130: SoccerBotCountry.PANAMA,
  131: SoccerBotCountry.PAPUA_NEW_GUINEA,
  132: SoccerBotCountry.PARAGUAY,
  133: SoccerBotCountry.PERU,
  134: SoccerBotCountry.PHILIPPINES,
  135: SoccerBotCountry.POLAND,
  136: SoccerBotCountry.PORTUGAL,
  228: SoccerBotCountry.PUERTO_RICO,
  249: SoccerBotCountry.REUNION,
  140: SoccerBotCountry.ROMANIA,
  141: SoccerBotCountry.RUSSIA,
  139: SoccerBotCountry.RWANDA,
  143: SoccerBotCountry.SAMOA,
  144: SoccerBotCountry.SAN_MARINO,
  145: SoccerBotCountry.SAO_TOME_AND_PRINCIPE,
  146: SoccerBotCountry.SAUDI_ARABIA,
  190: SoccerBotCountry.SCOTLAND,
  149: SoccerBotCountry.SENEGAL,
  215: SoccerBotCountry.SERBIA,
  151: SoccerBotCountry.SEYCHELLES,
  152: SoccerBotCountry.SIERRA_LEONE,
  153: SoccerBotCountry.SINGAPORE,
  154: SoccerBotCountry.SLOVAKIA,
  155: SoccerBotCountry.SLOVENIA,
  69: SoccerBotCountry.SOLOMON_ISLANDS,
  159: SoccerBotCountry.SOUTH_AFRICA,
  262: SoccerBotCountry.SOUTH_SUDAN,
  157: SoccerBotCountry.SPAIN,
  158: SoccerBotCountry.SRI_LANKA,
  225: SoccerBotCountry.SAINT_KITS_AND_NEVIS,
  230: SoccerBotCountry.SAINT_LUCIA,
  224: SoccerBotCountry.SAINT_VINCENT_AND_THE_GRENADINES,
  160: SoccerBotCountry.SUDAN,
  161: SoccerBotCountry.SURINAME,
  147: SoccerBotCountry.SWEDEN,
  148: SoccerBotCountry.SWITZERLAND,
  163: SoccerBotCountry.SYRIA,
  237: SoccerBotCountry.TAHITI,
  165: SoccerBotCountry.TAJIKISTAN,
  166: SoccerBotCountry.TANZANIA,
  167: SoccerBotCountry.THAILAND,
  52: SoccerBotCountry.GAMBIA,
  168: SoccerBotCountry.TOGO,
  169: SoccerBotCountry.TONGA,
  170: SoccerBotCountry.TRINIDAD_AND_TOBAGO,
  173: SoccerBotCountry.TUNISIA,
  174: SoccerBotCountry.TURKEY,
  175: SoccerBotCountry.TURKMENISTAN,
  226: SoccerBotCountry.TURKS_AND_CAICOS_ISLANDS,
  247: SoccerBotCountry.TUVALU,
  176: SoccerBotCountry.UGANDA,
  177: SoccerBotCountry.UKRAINE,
  183: SoccerBotCountry.UNITED_ARAB_EMIRATES,
  184: SoccerBotCountry.UNITED_STATES,
  179: SoccerBotCountry.URUGUAY,
  180: SoccerBotCountry.UZBEKISTAN,
  181: SoccerBotCountry.VANUATU,
  182: SoccerBotCountry.VENEZUELA,
  185: SoccerBotCountry.VIETNAM,
  191: SoccerBotCountry.WALES,
  186: SoccerBotCountry.YEMEN,
  142: SoccerBotCountry.ZAMBIA,
  253: SoccerBotCountry.ZANZIBAR,
  187: SoccerBotCountry.ZIMBABWE
};

export const SOCCERWAY_COUNTRY: { [key: string]: SoccerBotCountry } = {
  Afghanistan: SoccerBotCountry.AFGHANISTAN,
  Albania: SoccerBotCountry.ALBANIA,
  Algeria: SoccerBotCountry.ALGERIA,
  'American Samoa': SoccerBotCountry.AMERICAN_SAMOA,
  Andorra: SoccerBotCountry.ANDORRA,
  Angola: SoccerBotCountry.ANGUILLA,
  Antigua_and_Barbuda: SoccerBotCountry.ANTIGUA_AND_BARBUDA,
  Argentina: SoccerBotCountry.ARGENTINA,
  Armenia: SoccerBotCountry.ARMENIA,
  Aruba: SoccerBotCountry.ARUBA,
  Australia: SoccerBotCountry.AUSTRALIA,
  Austria: SoccerBotCountry.AUSTRIA,
  Azerbaijan: SoccerBotCountry.AZERBAIJAN,
  Bahrain: SoccerBotCountry.BAHRAIN,
  Bangladesh: SoccerBotCountry.BANGLADESH,
  Barbados: SoccerBotCountry.BARBADOS,
  Belarus: SoccerBotCountry.BELARUS,
  Belgium: SoccerBotCountry.BELGIUM,
  Belize: SoccerBotCountry.BELIZE,
  Benin: SoccerBotCountry.BENIN,
  Bermuda: SoccerBotCountry.BERMUDA,
  Bhutan: SoccerBotCountry.BHUTAN,
  Bolivia: SoccerBotCountry.BOLIVIA,
  'Bosnia and Herzegovina': SoccerBotCountry.BOSNIA_AND_HERZEGOVINA,
  Botswana: SoccerBotCountry.BOTSWANA,
  Brazil: SoccerBotCountry.BRAZIL,
  'British Virgin Islands': SoccerBotCountry.BRITISH_VIRGIN_ISLANDS,
  'Brunei Darussalam': SoccerBotCountry.BRUNEI,
  Bulgaria: SoccerBotCountry.BULGARIA,
  'Burkina Faso': SoccerBotCountry.BURKINA_FASO,
  Burundi: SoccerBotCountry.BURUNDI,
  Cambodia: SoccerBotCountry.CAMBODIA,
  Cameroon: SoccerBotCountry.CAMEROON,
  Canada: SoccerBotCountry.CANADA,
  'Cape Verde Islands': SoccerBotCountry.CAPE_VERDE,
  'Cayman Islands': SoccerBotCountry.CAYMAN_ISLANDS,
  'Central African Republic': SoccerBotCountry.CENTRAL_AFRICAN_REPUBLIC,
  Chad: SoccerBotCountry.CHAD,
  Chile: SoccerBotCountry.CHILE,
  'China PR': SoccerBotCountry.CHINA,
  'Chinese Taipei': SoccerBotCountry.CHINESE_TAIPEI,
  Colombia: SoccerBotCountry.COLOMBIA,
  'Congo DR': SoccerBotCountry.DR_CONGO,
  Congo: SoccerBotCountry.CONGO,
  'Cook Islands': SoccerBotCountry.COOK_ISLANDS,
  'Costa Rica': SoccerBotCountry.COSTA_RICA,
  "Côte d'Ivoire": SoccerBotCountry.IVORY_COAST,
  Croatia: SoccerBotCountry.CROATIA,
  Cuba: SoccerBotCountry.CUBA,
  Curaçao: SoccerBotCountry.CURACAO,
  Cyprus: SoccerBotCountry.CYPRUS,
  'Czech Republic': SoccerBotCountry.CZECH_REPUBLIC,
  Denmark: SoccerBotCountry.DENMARK,
  Djibouti: SoccerBotCountry.DJIBOUTI,
  'Dominican Republic': SoccerBotCountry.DOMINICA,
  Ecuador: SoccerBotCountry.ECUADOR,
  Egypt: SoccerBotCountry.EGYPT,
  'El Salvador': SoccerBotCountry.EL_SALVADOR,
  England: SoccerBotCountry.ENGLAND,
  Eritrea: SoccerBotCountry.ERITREA,
  Estonia: SoccerBotCountry.ESTONIA,
  Eswatini: SoccerBotCountry.ESWATINI,
  Ethiopia: SoccerBotCountry.ETHIOPIA,
  'Faroe Islands': SoccerBotCountry.FAROE_ISLANDS,
  Fiji: SoccerBotCountry.FIJI,
  Finland: SoccerBotCountry.FINLAND,
  France: SoccerBotCountry.FRANCE,
  'French Guiana': SoccerBotCountry.FRENCH_GUIANA,
  Gabon: SoccerBotCountry.GABON,
  Gambia: SoccerBotCountry.GAMBIA,
  Georgia: SoccerBotCountry.GEORGIA,
  Germany: SoccerBotCountry.GERMANY,
  Ghana: SoccerBotCountry.GHANA,
  Gibraltar: SoccerBotCountry.GIBRALTAR,
  Greece: SoccerBotCountry.GREECE,
  Grenada: SoccerBotCountry.GRENADA,
  Guadeloupe: SoccerBotCountry.GUADELOUPE,
  Guam: SoccerBotCountry.GUAM,
  Guatemala: SoccerBotCountry.GUATEMALA,
  Guinea: SoccerBotCountry.GUINEA,
  Guyana: SoccerBotCountry.GUYANA,
  Haiti: SoccerBotCountry.HAITI,
  Honduras: SoccerBotCountry.HONDURAS,
  'Hong Kong': SoccerBotCountry.HONG_KONG,
  Hungary: SoccerBotCountry.HUNGARY,
  Iceland: SoccerBotCountry.ICELAND,
  India: SoccerBotCountry.INDIA,
  Indonesia: SoccerBotCountry.INDONESIA,
  Iran: SoccerBotCountry.IRAN,
  Iraq: SoccerBotCountry.IRAQ,
  Israel: SoccerBotCountry.ISRAEL,
  Italy: SoccerBotCountry.ITALY,
  Jamaica: SoccerBotCountry.JAMAICA,
  Japan: SoccerBotCountry.JAPAN,
  Jordan: SoccerBotCountry.JORDAN,
  Kazakhstan: SoccerBotCountry.KAZAKHSTAN,
  Kenya: SoccerBotCountry.KENYA,
  'Korea Republic': SoccerBotCountry.SOUTH_KOREA,
  Kosovo: SoccerBotCountry.KOSOVO,
  Kuwait: SoccerBotCountry.KUWAIT,
  'Kyrgyz Republic': SoccerBotCountry.KYRGYZSTAN,
  Laos: SoccerBotCountry.LAOS,
  Latvia: SoccerBotCountry.LATVIA,
  Lebanon: SoccerBotCountry.LEBANON,
  Lesotho: SoccerBotCountry.LESOTHO,
  Liberia: SoccerBotCountry.LIBERIA,
  Libya: SoccerBotCountry.LIBYA,
  Liechtenstein: SoccerBotCountry.LIECHTENSTEIN,
  Lithuania: SoccerBotCountry.LITHUANIA,
  Luxembourg: SoccerBotCountry.LUXEMBOURG,
  Macao: SoccerBotCountry.MACAU,
  Madagascar: SoccerBotCountry.MADAGASCAR,
  Malawi: SoccerBotCountry.MALAWI,
  Malaysia: SoccerBotCountry.MALAYSIA,
  Maldives: SoccerBotCountry.MALDIVES,
  Mali: SoccerBotCountry.MALI,
  Malta: SoccerBotCountry.MALTA,
  Martinique: SoccerBotCountry.MARTINIQUE,
  Mauritania: SoccerBotCountry.MAURITANIA,
  Mauritius: SoccerBotCountry.MAURITIUS,
  Mexico: SoccerBotCountry.MEXICO,
  Moldova: SoccerBotCountry.MOLDOVA,
  Mongolia: SoccerBotCountry.MONGOLIA,
  Montenegro: SoccerBotCountry.MONTENEGRO,
  Morocco: SoccerBotCountry.MOROCCO,
  Mozambique: SoccerBotCountry.MOZAMBIQUE,
  Myanmar: SoccerBotCountry.MYANMAR,
  Nepal: SoccerBotCountry.NEPAL,
  Netherlands: SoccerBotCountry.NETHERLANDS,
  'New Caledonia': SoccerBotCountry.NEW_CALEDONIA,
  'New Zealand': SoccerBotCountry.NEW_ZEALAND,
  Nicaragua: SoccerBotCountry.NICARAGUA,
  Niger: SoccerBotCountry.NIGER,
  Nigeria: SoccerBotCountry.NIGERIA,
  'North Macedonia': SoccerBotCountry.MACEDONIA,
  'Northern Ireland': SoccerBotCountry.NORTHERN_IRELAND,
  Norway: SoccerBotCountry.NORWAY,
  Oman: SoccerBotCountry.OMAN,
  Pakistan: SoccerBotCountry.PAKISTAN,
  Palestine: SoccerBotCountry.PALESTINE,
  Panama: SoccerBotCountry.PANAMA,
  'Papua New Guinea': SoccerBotCountry.PAPUA_NEW_GUINEA,
  Paraguay: SoccerBotCountry.PARAGUAY,
  Peru: SoccerBotCountry.PERU,
  Philippines: SoccerBotCountry.PHILIPPINES,
  Poland: SoccerBotCountry.POLAND,
  Portugal: SoccerBotCountry.PORTUGAL,
  'Puerto Rico': SoccerBotCountry.PUERTO_RICO,
  Qatar: SoccerBotCountry.QATAR,
  'Republic of Ireland': SoccerBotCountry.IRELAND,
  Réunion: SoccerBotCountry.REUNION,
  Romania: SoccerBotCountry.ROMANIA,
  Russia: SoccerBotCountry.RUSSIA,
  Rwanda: SoccerBotCountry.RWANDA,
  Samoa: SoccerBotCountry.SAMOA,
  'San Marino': SoccerBotCountry.SAN_MARINO,
  'São Tomé e Príncipe': SoccerBotCountry.SAO_TOME_AND_PRINCIPE,
  'Saudi Arabia': SoccerBotCountry.SAUDI_ARABIA,
  Scotland: SoccerBotCountry.SCOTLAND,
  Senegal: SoccerBotCountry.SENEGAL,
  Serbia: SoccerBotCountry.SERBIA,
  'Sierra Leone': SoccerBotCountry.SIERRA_LEONE,
  Singapore: SoccerBotCountry.SINGAPORE,
  Slovakia: SoccerBotCountry.SLOVAKIA,
  Slovenia: SoccerBotCountry.SLOVENIA,
  'Solomon Islands': SoccerBotCountry.SOLOMON_ISLANDS,
  Somalia: SoccerBotCountry.SOMALIA,
  'South Africa': SoccerBotCountry.SOUTH_AFRICA,
  Spain: SoccerBotCountry.SPAIN,
  'Sri Lanka': SoccerBotCountry.SRI_LANKA,
  'St. Kitts and Nevis': SoccerBotCountry.SAINT_KITS_AND_NEVIS,
  Sudan: SoccerBotCountry.SUDAN,
  Suriname: SoccerBotCountry.SURINAME,
  Sweden: SoccerBotCountry.SWEDEN,
  Switzerland: SoccerBotCountry.SWITZERLAND,
  Syria: SoccerBotCountry.SYRIA,
  Tahiti: SoccerBotCountry.TAHITI,
  Tajikistan: SoccerBotCountry.TAJIKISTAN,
  Tanzania: SoccerBotCountry.TANZANIA,
  Thailandt: SoccerBotCountry.THAILAND,
  Togo: SoccerBotCountry.TOGO,
  'Trinidad and Tobago': SoccerBotCountry.TRINIDAD_AND_TOBAGO,
  Tunisia: SoccerBotCountry.TUNISIA,
  Turkey: SoccerBotCountry.TURKEY,
  Turkmenistan: SoccerBotCountry.TURKMENISTAN,
  'Turks and Caicos Islands': SoccerBotCountry.TURKS_AND_CAICOS_ISLANDS,
  Uganda: SoccerBotCountry.UGANDA,
  Ukraine: SoccerBotCountry.UKRAINE,
  'United Arab Emirates': SoccerBotCountry.UNITED_ARAB_EMIRATES,
  Uruguay: SoccerBotCountry.URUGUAY,
  USA: SoccerBotCountry.UNITED_STATES,
  Uzbekistan: SoccerBotCountry.UZBEKISTAN,
  Venezuela: SoccerBotCountry.VENEZUELA,
  Vietnam: SoccerBotCountry.VIETNAM,
  Wales: SoccerBotCountry.WALES,
  Yemen: SoccerBotCountry.YEMEN,
  Zambia: SoccerBotCountry.ZAMBIA,
  Zimbabwe: SoccerBotCountry.ZIMBABWE
};

export const EUROFOTBAL_COUNTRY: { [key: string]: SoccerBotCountry } = {
  Afghánistán: SoccerBotCountry.AFGHANISTAN,
  Albánie: SoccerBotCountry.ALBANIA,
  Alžírsko: SoccerBotCountry.ALGERIA,
  'Americká Samoa': SoccerBotCountry.AMERICAN_SAMOA,
  Andorra: SoccerBotCountry.ANDORRA,
  Anglie: SoccerBotCountry.ENGLAND,
  Angola: SoccerBotCountry.ANGOLA,
  Anguilla: SoccerBotCountry.ANGUILLA,
  'Antigua a Barbuda': SoccerBotCountry.ANTIGUA_AND_BARBUDA,
  Argentina: SoccerBotCountry.ARGENTINA,
  Arménie: SoccerBotCountry.ARMENIA,
  Aruba: SoccerBotCountry.ARUBA,
  Austrálie: SoccerBotCountry.AUSTRALIA,
  Ázerbájdžán: SoccerBotCountry.AZERBAIJAN,
  Bahrain: SoccerBotCountry.BAHRAIN,
  Bangladéš: SoccerBotCountry.BANGLADESH,
  Barbados: SoccerBotCountry.BARBADOS,
  Belgie: SoccerBotCountry.BELGIUM,
  Belize: SoccerBotCountry.BELIZE,
  Bělorusko: SoccerBotCountry.BELARUS,
  Benin: SoccerBotCountry.BENIN,
  Bermudy: SoccerBotCountry.BERMUDA,
  Bhútán: SoccerBotCountry.BHUTAN,
  Bolívie: SoccerBotCountry.BOLIVIA,
  'Bosna a Hercegovina': SoccerBotCountry.BOSNIA_AND_HERZEGOVINA,
  Botswana: SoccerBotCountry.BOTSWANA,
  Brazílie: SoccerBotCountry.BRAZIL,
  'Britské Panenské ostrovy': SoccerBotCountry.BRITISH_VIRGIN_ISLANDS,
  Brunej: SoccerBotCountry.BRUNEI,
  Bulharsko: SoccerBotCountry.BULGARIA,
  'Burkina Faso': SoccerBotCountry.BURKINA_FASO,
  Burundi: SoccerBotCountry.BURUNDI,
  Čad: SoccerBotCountry.CHAD,
  'Černá Hora': SoccerBotCountry.MONTENEGRO,
  Česko: SoccerBotCountry.CZECH_REPUBLIC,
  Chile: SoccerBotCountry.CHILE,
  Chorvatsko: SoccerBotCountry.CROATIA,
  Čína: SoccerBotCountry.CHINA,
  'Cookovy ostrovy': SoccerBotCountry.COOK_ISLANDS,
  Curaçao: SoccerBotCountry.CURACAO,
  Dánsko: SoccerBotCountry.DENMARK,
  'Demokratická republika Kongo': SoccerBotCountry.DR_CONGO,
  Dominika: SoccerBotCountry.DOMINICA,
  'Dominikánská republika': SoccerBotCountry.DOMINICAN_REPUBLIC,
  Džibutsko: SoccerBotCountry.DJIBOUTI,
  Egypt: SoccerBotCountry.EGYPT,
  Ekvádor: SoccerBotCountry.ECUADOR,
  Eritrea: SoccerBotCountry.ERITREA,
  Estonsko: SoccerBotCountry.ESTONIA,
  eSwatini: SoccerBotCountry.ESWATINI,
  Etiopie: SoccerBotCountry.ETHIOPIA,
  'Faerské ostrovy': SoccerBotCountry.FAROE_ISLANDS,
  Fidži: SoccerBotCountry.FIJI,
  Filipíny: SoccerBotCountry.PHILIPPINES,
  Finsko: SoccerBotCountry.FINLAND,
  Francie: SoccerBotCountry.FRANCE,
  'Francouzská Guyana': SoccerBotCountry.FRENCH_GUIANA,
  Gabon: SoccerBotCountry.GABON,
  Gambie: SoccerBotCountry.GAMBIA,
  Ghana: SoccerBotCountry.GHANA,
  Gibraltar: SoccerBotCountry.GIBRALTAR,
  Grenada: SoccerBotCountry.GRENADA,
  Gruzie: SoccerBotCountry.GEORGIA,
  Guadeloupe: SoccerBotCountry.GUADELOUPE,
  Guam: SoccerBotCountry.GUAM,
  Guatemala: SoccerBotCountry.GUATEMALA,
  'Guinea Bissau': SoccerBotCountry.GUINEA_BISSAU,
  Guinea: SoccerBotCountry.GUINEA,
  Guyana: SoccerBotCountry.GUYANA,
  Haiti: SoccerBotCountry.HAITI,
  Honduras: SoccerBotCountry.HONDURAS,
  Hongkong: SoccerBotCountry.HONG_KONG,
  Indie: SoccerBotCountry.INDIA,
  Indonésie: SoccerBotCountry.INDONESIA,
  Irák: SoccerBotCountry.IRAN,
  Írán: SoccerBotCountry.IRAQ,
  Irsko: SoccerBotCountry.IRELAND,
  Island: SoccerBotCountry.ICELAND,
  Itálie: SoccerBotCountry.ITALY,
  Izrael: SoccerBotCountry.ISRAEL,
  Jamajka: SoccerBotCountry.JAMAICA,
  Japonsko: SoccerBotCountry.JAPAN,
  Jemen: SoccerBotCountry.YEMEN,
  'Jihoafrická republika': SoccerBotCountry.SOUTH_AFRICA,
  'Jižní Súdán': SoccerBotCountry.SOUTH_SUDAN,
  Jordánsko: SoccerBotCountry.JORDAN,
  'Kajmanské ostrovy': SoccerBotCountry.CAYMAN_ISLANDS,
  Kambodža: SoccerBotCountry.CAMBODIA,
  Kamerun: SoccerBotCountry.CAMEROON,
  Kanada: SoccerBotCountry.CANADA,
  Kapverdy: SoccerBotCountry.CAPE_VERDE,
  Katar: SoccerBotCountry.QATAR,
  Kazachstán: SoccerBotCountry.KAZAKHSTAN,
  Keňa: SoccerBotCountry.KENYA,
  Kiribati: SoccerBotCountry.KIRIBATI,
  Kolumbie: SoccerBotCountry.COLOMBIA,
  Komory: SoccerBotCountry.COMOROS,
  Kongo: SoccerBotCountry.CONGO,
  'Korejská lidově demokratická republika': SoccerBotCountry.NORTH_KOREA,
  'Korejská republika': SoccerBotCountry.SOUTH_KOREA,
  Kosovo: SoccerBotCountry.KOSOVO,
  Kostarika: SoccerBotCountry.COSTA_RICA,
  Kuba: SoccerBotCountry.CUBA,
  Kuvajt: SoccerBotCountry.KUWAIT,
  Kypr: SoccerBotCountry.CYPRUS,
  Kyrgyzstán: SoccerBotCountry.KYRGYZSTAN,
  Laos: SoccerBotCountry.LAOS,
  Lesotho: SoccerBotCountry.LESOTHO,
  Libanon: SoccerBotCountry.LEBANON,
  Libérie: SoccerBotCountry.LIBERIA,
  Libye: SoccerBotCountry.LIBYA,
  Lichtenštejnsko: SoccerBotCountry.LIECHTENSTEIN,
  Litva: SoccerBotCountry.LITHUANIA,
  Lotyšsko: SoccerBotCountry.LATVIA,
  Lucembursko: SoccerBotCountry.LUXEMBOURG,
  Macao: SoccerBotCountry.MACAU,
  Madagaskar: SoccerBotCountry.MADAGASCAR,
  Maďarsko: SoccerBotCountry.HUNGARY,
  Malajsie: SoccerBotCountry.MALAYSIA,
  Malawi: SoccerBotCountry.MALAWI,
  Maledivy: SoccerBotCountry.MALDIVES,
  Mali: SoccerBotCountry.MALI,
  Malta: SoccerBotCountry.MALTA,
  Maroko: SoccerBotCountry.MOROCCO,
  Martinik: SoccerBotCountry.MARTINIQUE,
  Mauritánie: SoccerBotCountry.MAURITANIA,
  Mauritius: SoccerBotCountry.MAURITIUS,
  Mexiko: SoccerBotCountry.MEXICO,
  Mikronésie: SoccerBotCountry.MICRONESIA,
  Moldavsko: SoccerBotCountry.MOLDOVA,
  Mongolsko: SoccerBotCountry.MONGOLIA,
  Montserrat: SoccerBotCountry.MONTSERRAT,
  Mozambik: SoccerBotCountry.MOZAMBIQUE,
  Myanmar: SoccerBotCountry.MYANMAR,
  Německo: SoccerBotCountry.GERMANY,
  Nepál: SoccerBotCountry.NEPAL,
  Niger: SoccerBotCountry.NIGER,
  Nigérie: SoccerBotCountry.NIGERIA,
  Nikaragua: SoccerBotCountry.NICARAGUA,
  Nizozemsko: SoccerBotCountry.NETHERLANDS,
  Norsko: SoccerBotCountry.NORWAY,
  'Nová Kaledonie': SoccerBotCountry.NEW_CALEDONIA,
  'Nový Zéland': SoccerBotCountry.NEW_ZEALAND,
  Omán: SoccerBotCountry.OMAN,
  Pákistán: SoccerBotCountry.PAKISTAN,
  Palau: SoccerBotCountry.PALAU,
  Palestina: SoccerBotCountry.PALESTINE,
  Panama: SoccerBotCountry.PANAMA,
  'Panenské ostrovy USA': SoccerBotCountry.US_VIRGIN_ISLANDS,
  'Papua Nová Guinea': SoccerBotCountry.PAPUA_NEW_GUINEA,
  Paraguay: SoccerBotCountry.PARAGUAY,
  Peru: SoccerBotCountry.PERU,
  'Pobřeží slonoviny': SoccerBotCountry.IVORY_COAST,
  Polsko: SoccerBotCountry.POLAND,
  Portoriko: SoccerBotCountry.PUERTO_RICO,
  Portugalsko: SoccerBotCountry.PORTUGAL,
  Rakousko: SoccerBotCountry.AUSTRIA,
  Řecko: SoccerBotCountry.GREECE,
  Réunion: SoccerBotCountry.REUNION,
  'Rovníková Guinea': SoccerBotCountry.EQUATORIAL_GUINEA,
  Rumunsko: SoccerBotCountry.ROMANIA,
  Rusko: SoccerBotCountry.RUSSIA,
  Rwanda: SoccerBotCountry.RWANDA,
  'Saint Martin': SoccerBotCountry.SAINT_MARTIN,
  'Šalamounovy ostrovy': SoccerBotCountry.SOLOMON_ISLANDS,
  Salvador: SoccerBotCountry.EL_SALVADOR,
  Samoa: SoccerBotCountry.SAMOA,
  'San Marino': SoccerBotCountry.SAN_MARINO,
  'Saúdská Arábie': SoccerBotCountry.SAUDI_ARABIA,
  Senegal: SoccerBotCountry.SENEGAL,
  'Severní Irsko': SoccerBotCountry.NORTHERN_IRELAND,
  'Severní Makedonie': SoccerBotCountry.MACEDONIA,
  'Severní Mariany': SoccerBotCountry.NORTHERN_MARIANA_ISLANDS,
  Seychelly: SoccerBotCountry.SEYCHELLES,
  'Sierra Leone': SoccerBotCountry.SIERRA_LEONE,
  Singapur: SoccerBotCountry.SINGAPORE,
  'Sint Maarten': SoccerBotCountry.SINT_MAARTEN,
  Skotsko: SoccerBotCountry.SCOTLAND,
  Slovensko: SoccerBotCountry.SLOVAKIA,
  Slovinsko: SoccerBotCountry.SLOVENIA,
  Somálsko: SoccerBotCountry.SOMALIA,
  Španělsko: SoccerBotCountry.SPAIN,
  'Spojené arabské emiráty': SoccerBotCountry.UNITED_ARAB_EMIRATES,
  Srbsko: SoccerBotCountry.SERBIA,
  'Srí Lanka': SoccerBotCountry.SRI_LANKA,
  'Středoafrická republika': SoccerBotCountry.CENTRAL_AFRICAN_REPUBLIC,
  Súdán: SoccerBotCountry.SUDAN,
  Surinam: SoccerBotCountry.SURINAME,
  'Svatá Lucie': SoccerBotCountry.SAINT_LUCIA,
  'Svatý Kryštof a Nevis': SoccerBotCountry.SAINT_KITS_AND_NEVIS,
  'Svatý Tomáš a Princův ostrov': SoccerBotCountry.SAO_TOME_AND_PRINCIPE,
  'Svatý Vincent a Grenadiny': SoccerBotCountry.SAINT_VINCENT_AND_THE_GRENADINES,
  Švédsko: SoccerBotCountry.SWEDEN,
  Švýcarsko: SoccerBotCountry.SWITZERLAND,
  Sýrie: SoccerBotCountry.SYRIA,
  Tádžikistán: SoccerBotCountry.TAJIKISTAN,
  Tahiti: SoccerBotCountry.TAHITI,
  Tanzanie: SoccerBotCountry.TANZANIA,
  'Tchaj-wan': SoccerBotCountry.CHINESE_TAIPEI,
  Thajsko: SoccerBotCountry.THAILAND,
  Togo: SoccerBotCountry.TOGO,
  Tonga: SoccerBotCountry.TONGA,
  'Trinidad a Tobago': SoccerBotCountry.TRINIDAD_AND_TOBAGO,
  Tunisko: SoccerBotCountry.TUNISIA,
  Turecko: SoccerBotCountry.TURKEY,
  Turkmenistán: SoccerBotCountry.TURKMENISTAN,
  'Turks a Caicos': SoccerBotCountry.TURKS_AND_CAICOS_ISLANDS,
  Tuvalu: SoccerBotCountry.TUVALU,
  Uganda: SoccerBotCountry.UGANDA,
  Ukrajina: SoccerBotCountry.UKRAINE,
  Uruguay: SoccerBotCountry.URUGUAY,
  USA: SoccerBotCountry.UNITED_STATES,
  Uzbekistán: SoccerBotCountry.UZBEKISTAN,
  Vanuatu: SoccerBotCountry.VANUATU,
  Venezuela: SoccerBotCountry.VENEZUELA,
  Vietnam: SoccerBotCountry.VIETNAM,
  'Východní Timor': SoccerBotCountry.TIMOR_LESTE,
  Wales: SoccerBotCountry.WALES,
  Zambie: SoccerBotCountry.ZAMBIA,
  Zanzibar: SoccerBotCountry.ZANZIBAR,
  Zimbabwe: SoccerBotCountry.ZIMBABWE
};

export const SPORTNET_COUNTRY: { [key: string]: SoccerBotCountry } = {
  Slovensko: SoccerBotCountry.SLOVAKIA,
  Afganistan: SoccerBotCountry.AFGHANISTAN,
  // 'Alandy': SoccerBotCountry.,
  Albánsko: SoccerBotCountry.ALBANIA,
  Alžírsko: SoccerBotCountry.ALGERIA,
  'Americká Samoa': SoccerBotCountry.AMERICAN_SAMOA,
  'Americké Panenské ostrovy': SoccerBotCountry.US_VIRGIN_ISLANDS,
  Andorra: SoccerBotCountry.ANDORRA,
  Anglicko: SoccerBotCountry.ENGLAND,
  Angola: SoccerBotCountry.ANGOLA,
  Anguilla: SoccerBotCountry.ANGUILLA,
  // 'Antarktída': SoccerBotCountry.,
  'Antigua a Barbuda': SoccerBotCountry.ANTIGUA_AND_BARBUDA,
  Argentína: SoccerBotCountry.ARGENTINA,
  Arménsko: SoccerBotCountry.ARMENIA,
  Aruba: SoccerBotCountry.ARUBA,
  Austrália: SoccerBotCountry.AUSTRALIA,
  Azerbajdžan: SoccerBotCountry.AZERBAIJAN,
  Bahamy: SoccerBotCountry.BAHAMAS,
  Bahrajn: SoccerBotCountry.BAHRAIN,
  Bangladéš: SoccerBotCountry.BANGLADESH,
  Barbados: SoccerBotCountry.BARBADOS,
  Belgicko: SoccerBotCountry.BELGIUM,
  Belize: SoccerBotCountry.BELIZE,
  Benin: SoccerBotCountry.BENIN,
  Bermudy: SoccerBotCountry.BERMUDA,
  Bhután: SoccerBotCountry.BHUTAN,
  Bielorusko: SoccerBotCountry.BELARUS,
  Bolívia: SoccerBotCountry.BOLIVIA,
  'Bonaire, Svätý Eustach a Saba': SoccerBotCountry.BONAIRE,
  'Bosna a Hercegovina': SoccerBotCountry.BOSNIA_AND_HERZEGOVINA,
  Botswana: SoccerBotCountry.BOTSWANA,
  // 'Bouvetov ostrov': SoccerBotCountry.,
  Brazília: SoccerBotCountry.BRAZIL,
  'Britské Panenské ostrovy': SoccerBotCountry.BRITISH_VIRGIN_ISLANDS,
  // 'Britské indickooceánske územie': SoccerBotCountry.,
  Brunej: SoccerBotCountry.BRUNEI,
  Bulharsko: SoccerBotCountry.BULGARIA,
  Burkina: SoccerBotCountry.BURKINA_FASO,
  Burundi: SoccerBotCountry.BURUNDI,
  Chorvátsko: SoccerBotCountry.CROATIA,
  'Cookove ostrovy': SoccerBotCountry.COOK_ISLANDS,
  Curaçao: SoccerBotCountry.CURACAO,
  Cyprus: SoccerBotCountry.CYPRUS,
  Dominika: SoccerBotCountry.DOMINICA,
  'Dominikánska republika': SoccerBotCountry.DOMINICAN_REPUBLIC,
  Dánsko: SoccerBotCountry.DENMARK,
  Džibutsko: SoccerBotCountry.DJIBOUTI,
  Egypt: SoccerBotCountry.EGYPT,
  Ekvádor: SoccerBotCountry.ECUADOR,
  Eritrea: SoccerBotCountry.ERITREA,
  Estónsko: SoccerBotCountry.ESTONIA,
  Etiópia: SoccerBotCountry.ETHIOPIA,
  'Faerské ostrovy': SoccerBotCountry.FAROE_ISLANDS,
  // 'Falklandy': SoccerBotCountry.,
  Fidži: SoccerBotCountry.FIJI,
  Filipíny: SoccerBotCountry.PHILIPPINES,
  'Francúzska Guyana': SoccerBotCountry.FRENCH_GUIANA,
  // 'Francúzska Polynézia': SoccerBotCountry.,
  // 'Francúzske južné územia': SoccerBotCountry.,
  Francúzsko: SoccerBotCountry.FRANCE,
  Fínsko: SoccerBotCountry.FINLAND,
  Gabon: SoccerBotCountry.GABON,
  Gambia: SoccerBotCountry.GAMBIA,
  Ghana: SoccerBotCountry.GHANA,
  Gibraltár: SoccerBotCountry.GIBRALTAR,
  Grenada: SoccerBotCountry.GRENADA,
  Gruzínsko: SoccerBotCountry.GEORGIA,
  Grécko: SoccerBotCountry.GREECE,
  // 'Grónsko': SoccerBotCountry.,
  Guadeloupe: SoccerBotCountry.GUADELOUPE,
  Guam: SoccerBotCountry.GUAM,
  Guatemala: SoccerBotCountry.GUATEMALA,
  // 'Guernsey': SoccerBotCountry.,
  Guinea: SoccerBotCountry.GUINEA,
  'Guinea-Bissau': SoccerBotCountry.GUINEA_BISSAU,
  Guyana: SoccerBotCountry.GUYANA,
  Haiti: SoccerBotCountry.HAITI,
  // 'Heardov ostrov a Macdonaldove ostrovy': SoccerBotCountry.,
  Holandsko: SoccerBotCountry.NETHERLANDS,
  Honduras: SoccerBotCountry.HONDURAS,
  Hongkong: SoccerBotCountry.HONG_KONG,
  India: SoccerBotCountry.INDIA,
  Indonézia: SoccerBotCountry.INDONESIA,
  Irak: SoccerBotCountry.IRAQ,
  Irán: SoccerBotCountry.IRAN,
  Island: SoccerBotCountry.ICELAND,
  Izrael: SoccerBotCountry.ISRAEL,
  Jamajka: SoccerBotCountry.JAMAICA,
  Japonsko: SoccerBotCountry.JAPAN,
  Jemen: SoccerBotCountry.YEMEN,
  // 'Jersey': SoccerBotCountry.,
  Jordánsko: SoccerBotCountry.JORDAN,
  // 'Juhoslávia': SoccerBotCountry.,
  'Južná Afrika': SoccerBotCountry.SOUTH_AFRICA,
  // 'Južná Georgia a Južné Sandwichove ostrovy': SoccerBotCountry.,
  'Južný Sudán': SoccerBotCountry.SOUTH_SUDAN,
  'Kajmanie ostrovy': SoccerBotCountry.CAYMAN_ISLANDS,
  Kambodža: SoccerBotCountry.CAMBODIA,
  Kamerun: SoccerBotCountry.CAMEROON,
  Kanada: SoccerBotCountry.CANADA,
  Kapverdy: SoccerBotCountry.CAPE_VERDE,
  Katar: SoccerBotCountry.QATAR,
  Kazachstan: SoccerBotCountry.KAZAKHSTAN,
  Keňa: SoccerBotCountry.KENYA,
  Kirgizsko: SoccerBotCountry.KYRGYZSTAN,
  Kiribati: SoccerBotCountry.KIRIBATI,
  // 'Kokosové ostrovy': SoccerBotCountry.,
  Kolumbia: SoccerBotCountry.COLOMBIA,
  Komory: SoccerBotCountry.COMOROS,
  Kongo: SoccerBotCountry.CONGO,
  'Konžská demokratická republika': SoccerBotCountry.DR_CONGO,
  Kosovo: SoccerBotCountry.KOSOVO,
  Kostarika: SoccerBotCountry.COSTA_RICA,
  Kuba: SoccerBotCountry.CURACAO,
  Kuvajt: SoccerBotCountry.KUWAIT,
  'Kórejská republika': SoccerBotCountry.SOUTH_KOREA,
  'Kórejská ľudovodemokratická republika': SoccerBotCountry.NORTH_KOREA,
  Laos: SoccerBotCountry.LAOS,
  Lesotho: SoccerBotCountry.LESOTHO,
  Libanon: SoccerBotCountry.LEBANON,
  Libéria: SoccerBotCountry.LIBERIA,
  Lichtenštajnsko: SoccerBotCountry.LIECHTENSTEIN,
  Litva: SoccerBotCountry.LITHUANIA,
  Lotyšsko: SoccerBotCountry.LATVIA,
  Luxembursko: SoccerBotCountry.LUXEMBOURG,
  Líbya: SoccerBotCountry.LIBYA,
  Macao: SoccerBotCountry.MACAU,
  Macedónsko: SoccerBotCountry.MACEDONIA,
  Madagaskar: SoccerBotCountry.MADAGASCAR,
  Malajzia: SoccerBotCountry.MALAYSIA,
  Malawi: SoccerBotCountry.MALAWI,
  Maldivy: SoccerBotCountry.MALDIVES,
  Mali: SoccerBotCountry.MALI,
  Malta: SoccerBotCountry.MALTA,
  // 'Man': SoccerBotCountry.,
  Maroko: SoccerBotCountry.MOROCCO,
  // 'Marshallove ostrovy': SoccerBotCountry.,
  Martinik: SoccerBotCountry.MARTINIQUE,
  Mauritánia: SoccerBotCountry.MAURITANIA,
  Maurícius: SoccerBotCountry.MAURITIUS,
  // 'Mayotte': SoccerBotCountry.,
  Maďarsko: SoccerBotCountry.HUNGARY,
  // 'Menšie odľahlé ostrovy USA': SoccerBotCountry.,
  Mexiko: SoccerBotCountry.MEXICO,
  Mikronézia: SoccerBotCountry.MICRONESIA,
  Mjanmarsko: SoccerBotCountry.MYANMAR,
  Moldavsko: SoccerBotCountry.MOLDOVA,
  // 'Monako': SoccerBotCountry.,
  Mongolsko: SoccerBotCountry.MONGOLIA,
  Montserrat: SoccerBotCountry.MONTSERRAT,
  Mozambik: SoccerBotCountry.MOZAMBIQUE,
  Namíbia: SoccerBotCountry.NAMIBIA,
  Nauru: SoccerBotCountry.NAURU,
  Nemecko: SoccerBotCountry.GERMANY,
  Nepál: SoccerBotCountry.NEPAL,
  Niger: SoccerBotCountry.NIGER,
  Nigéria: SoccerBotCountry.NIGERIA,
  Nikaragua: SoccerBotCountry.NICARAGUA,
  Niue: SoccerBotCountry.NIUE,
  // 'Norfolk': SoccerBotCountry.,
  'Nová Kaledónia': SoccerBotCountry.NEW_CALEDONIA,
  'Nový Zéland': SoccerBotCountry.NEW_ZEALAND,
  Nórsko: SoccerBotCountry.NORWAY,
  Omán: SoccerBotCountry.OMAN,
  Pakistan: SoccerBotCountry.PAKISTAN,
  Palau: SoccerBotCountry.PALAU,
  Palestína: SoccerBotCountry.PALESTINE,
  Panama: SoccerBotCountry.PANAMA,
  'Papua Nová-Guinea': SoccerBotCountry.PAPUA_NEW_GUINEA,
  Paraguaj: SoccerBotCountry.PARAGUAY,
  Peru: SoccerBotCountry.PERU,
  // 'Pitcairnove ostrovy': SoccerBotCountry.,
  'Pobrežie Slonoviny': SoccerBotCountry.IVORY_COAST,
  Portoriko: SoccerBotCountry.PUERTO_RICO,
  Portugalsko: SoccerBotCountry.PORTUGAL,
  Poľsko: SoccerBotCountry.POLAND,
  Rakúsko: SoccerBotCountry.AUSTRIA,
  'Rovníková Guinea': SoccerBotCountry.EQUATORIAL_GUINEA,
  Rumunsko: SoccerBotCountry.ROMANIA,
  Rusko: SoccerBotCountry.RUSSIA,
  Rwanda: SoccerBotCountry.RWANDA,
  Réunion: SoccerBotCountry.REUNION,
  // 'Saint Pierre a Miquelon': SoccerBotCountry.,
  Salvádor: SoccerBotCountry.EL_SALVADOR,
  Samoa: SoccerBotCountry.SAMOA,
  'San Maríno': SoccerBotCountry.SAN_MARINO,
  'Saudská Arábia': SoccerBotCountry.SAUDI_ARABIA,
  Senegal: SoccerBotCountry.SENEGAL,
  'Severné Mariány': SoccerBotCountry.NORTHERN_MARIANA_ISLANDS,
  'Severné Írsko': SoccerBotCountry.NORTHERN_IRELAND,
  Seychely: SoccerBotCountry.SEYCHELLES,
  'Sierra Leone': SoccerBotCountry.SIERRA_LEONE,
  Singapur: SoccerBotCountry.SINGAPORE,
  Slovinsko: SoccerBotCountry.SLOVENIA,
  Somálsko: SoccerBotCountry.SOMALIA,
  // 'Sovietsky zväz': SoccerBotCountry.,
  'Spojené arabské emiráty': SoccerBotCountry.UNITED_ARAB_EMIRATES,
  // 'Spojené kráľovstvo': SoccerBotCountry.,
  'Spojené štáty, USA': SoccerBotCountry.UNITED_STATES,
  Srbsko: SoccerBotCountry.SERBIA,
  // 'Srbsko a Čierna Hora': SoccerBotCountry.,
  'Srí Lanka': SoccerBotCountry.SRI_LANKA,
  'Stredoafrická republika': SoccerBotCountry.CENTRAL_AFRICAN_REPUBLIC,
  Sudán: SoccerBotCountry.SUDAN,
  Surinam: SoccerBotCountry.SURINAME,
  // 'Svalbard a Jan Mayen': SoccerBotCountry.,
  Svazijsko: SoccerBotCountry.ESWATINI,
  // 'Svätá Helena, Ascension': SoccerBotCountry.,
  'Svätá Lucia': SoccerBotCountry.SAINT_LUCIA,
  // 'Svätý Bartolomej': SoccerBotCountry.,
  'Svätý Krištof a Nevis': SoccerBotCountry.SAINT_KITS_AND_NEVIS,
  'Svätý Martin (francúzska časť)': SoccerBotCountry.SAINT_MARTIN,
  'Svätý Martin (holandská časť)': SoccerBotCountry.SINT_MAARTEN,
  'Svätý Tomáš a Princov ostrov': SoccerBotCountry.SAO_TOME_AND_PRINCIPE,
  'Svätý Vincent a Grenadíny': SoccerBotCountry.SAINT_VINCENT_AND_THE_GRENADINES,
  Sýria: SoccerBotCountry.SYRIA,
  Tadžikistan: SoccerBotCountry.TAJIKISTAN,
  Tahiti: SoccerBotCountry.TAHITI,
  Taiwan: SoccerBotCountry.CHINESE_TAIPEI,
  Taliansko: SoccerBotCountry.ITALY,
  Tanzánia: SoccerBotCountry.TANZANIA,
  Thajsko: SoccerBotCountry.THAILAND,
  Togo: SoccerBotCountry.TOGO,
  // 'Tokelau': SoccerBotCountry.,
  Tonga: SoccerBotCountry.TONGA,
  'Trinidad a Tobago': SoccerBotCountry.TRINIDAD_AND_TOBAGO,
  Tunisko: SoccerBotCountry.TUNISIA,
  Turecko: SoccerBotCountry.TURKEY,
  Turkménsko: SoccerBotCountry.TURKMENISTAN,
  'Turks a Caicos': SoccerBotCountry.TURKS_AND_CAICOS_ISLANDS,
  Tuvalu: SoccerBotCountry.TUVALU,
  Uganda: SoccerBotCountry.UGANDA,
  Ukrajina: SoccerBotCountry.UKRAINE,
  Uruguaj: SoccerBotCountry.URUGUAY,
  Uzbekistan: SoccerBotCountry.UZBEKISTAN,
  Vanuatu: SoccerBotCountry.VANUATU,
  // 'Vatikán': SoccerBotCountry.,
  Venezuela: SoccerBotCountry.VENEZUELA,
  // 'Vianočný ostrov': SoccerBotCountry.,
  Vietnam: SoccerBotCountry.VIETNAM,
  'Východný Timor': SoccerBotCountry.TIMOR_LESTE,
  Wales: SoccerBotCountry.WALES,
  // 'Wallis a Futuna': SoccerBotCountry.,
  Zambia: SoccerBotCountry.ZAMBIA,
  Zimbabwe: SoccerBotCountry.ZIMBABWE,
  // 'Západná Sahara': SoccerBotCountry.,
  Írsko: SoccerBotCountry.IRELAND,
  Čad: SoccerBotCountry.CHAD,
  Česko: SoccerBotCountry.CZECH_REPUBLIC,
  // 'Česko-Slovensko': SoccerBotCountry.,
  'Čierna Hora': SoccerBotCountry.MONTENEGRO,
  Čile: SoccerBotCountry.CHILE,
  Čína: SoccerBotCountry.CHINA,
  'Čínsky Tchaj-pej': SoccerBotCountry.CHINESE_TAIPEI,
  'Šalamúnove ostrovy': SoccerBotCountry.SOLOMON_ISLANDS,
  Škótsko: SoccerBotCountry.SCOTLAND,
  Španielsko: SoccerBotCountry.SPAIN,
  Švajčiarsko: SoccerBotCountry.SWITZERLAND,
  Švédsko: SoccerBotCountry.SWEDEN
};
