import { SoccerBotCountry } from "./interfaces";

export const TRANSFERMARKT_COUNTRY: { [key: number]: SoccerBotCountry } = {
  1: SoccerBotCountry.AFGHANISTAN,
  3: SoccerBotCountry.ALBANIA,
  4: SoccerBotCountry.ALGERIA,
  239: SoccerBotCountry.AMERICAN_SAMOA,
  234: SoccerBotCountry.US_VIRGIN_ISLANDS,
  5: SoccerBotCountry.ANDORRA,
  6: SoccerBotCountry.ANGOLA,
  232: SoccerBotCountry.ANGUILLA,
  7: SoccerBotCountry.ANTIGUA_AND_BARBUDA,
  9: SoccerBotCountry.ARGENTINA,
  10: SoccerBotCountry.ARMENIA,
  233: SoccerBotCountry.ARUBA,
  12: SoccerBotCountry.AUSTRALIA,
  127: SoccerBotCountry.AUSTRIA,
  13: SoccerBotCountry.AZERBAIJAN,
  14: SoccerBotCountry.BAHAMAS,
  15: SoccerBotCountry.BAHRAIN,
  16: SoccerBotCountry.BANGLADESH,
  17: SoccerBotCountry.BARBADOS,
  18: SoccerBotCountry.BELARUS,
  19: SoccerBotCountry.BELGIUM,
  20: SoccerBotCountry.BELIZE,
  21: SoccerBotCountry.BENIN,
  211: SoccerBotCountry.BERMUDA,
  22: SoccerBotCountry.BHUTAN,
  23: SoccerBotCountry.BOLIVIA,
  269: SoccerBotCountry.BONAIRE,
  24: SoccerBotCountry.BOSNIA_AND_HERZEGOVINA,
  25: SoccerBotCountry.BOTSWANA,
  26: SoccerBotCountry.BRAZIL,
  231: SoccerBotCountry.BRITISH_VIRGIN_ISLANDS,
  27: SoccerBotCountry.BRUNEI,
  28: SoccerBotCountry.BULGARIA,
  29: SoccerBotCountry.BURKINA_FASO,
  30: SoccerBotCountry.BURUNDI,
  79: SoccerBotCountry.CAMBODIA,
  31: SoccerBotCountry.CAMEROON,
  80: SoccerBotCountry.CANADA,
  32: SoccerBotCountry.CAPE_VERDE,
  229: SoccerBotCountry.CAYMAN_ISLANDS,
  138: SoccerBotCountry.CENTRAL_AFRICAN_REPUBLIC,
  171: SoccerBotCountry.CHAD,
  33: SoccerBotCountry.CHILE,
  34: SoccerBotCountry.CHINA,
  164: SoccerBotCountry.CHINESE_TAIPEI,
  83: SoccerBotCountry.COLOMBIA,
  35: SoccerBotCountry.COMOROS,
  85: SoccerBotCountry.CONGO,
  238: SoccerBotCountry.COOK_ISLANDS,
  36: SoccerBotCountry.COSTA_RICA,
  38: SoccerBotCountry.IVORY_COAST,
  37: SoccerBotCountry.CROATIA,
  88: SoccerBotCountry.CUBA,
  260: SoccerBotCountry.CURACAO,
  188: SoccerBotCountry.CYPRUS,
  172: SoccerBotCountry.CZECH_REPUBLIC,
  39: SoccerBotCountry.DENMARK,
  41: SoccerBotCountry.DJIBOUTI,
  42: SoccerBotCountry.DOMINICA,
  43: SoccerBotCountry.DOMINICAN_REPUBLIC,
  193: SoccerBotCountry.DR_CONGO,
  44: SoccerBotCountry.ECUADOR,
  2: SoccerBotCountry.EGYPT,
  45: SoccerBotCountry.EL_SALVADOR,
  189: SoccerBotCountry.ENGLAND,
  8: SoccerBotCountry.EQUATORIAL_GUINEA,
  46: SoccerBotCountry.ERITREA,
  47: SoccerBotCountry.ESTONIA,
  162: SoccerBotCountry.ESWATINI,
  11: SoccerBotCountry.ETHIOPIA,
  208: SoccerBotCountry.FAROE_ISLANDS,
  111: SoccerBotCountry.MICRONESIA,
  48: SoccerBotCountry.FIJI,
  49: SoccerBotCountry.FINLAND,
  50: SoccerBotCountry.FRANCE,
  252: SoccerBotCountry.FRENCH_GUIANA,
  51: SoccerBotCountry.GABON,
  53: SoccerBotCountry.GEORGIA,
  40: SoccerBotCountry.GERMANY,
  54: SoccerBotCountry.GHANA,
  266: SoccerBotCountry.GIBRALTAR,
  56: SoccerBotCountry.GREECE,
  55: SoccerBotCountry.GRENADA,
  251: SoccerBotCountry.GUADELOUPE,
  241: SoccerBotCountry.GUAM,
  58: SoccerBotCountry.GUATEMALA,
  59: SoccerBotCountry.GUINEA,
  60: SoccerBotCountry.GUINEA_BISSAU,
  61: SoccerBotCountry.GUYANA,
  62: SoccerBotCountry.HAITI,
  66: SoccerBotCountry.HONDURAS,
  218: SoccerBotCountry.HONG_KONG,
  178: SoccerBotCountry.HUNGARY,
  73: SoccerBotCountry.ICELAND,
  67: SoccerBotCountry.INDIA,
  68: SoccerBotCountry.INDONESIA,
  71: SoccerBotCountry.IRAN,
  70: SoccerBotCountry.IRAQ,
  72: SoccerBotCountry.IRELAND,
  74: SoccerBotCountry.ISRAEL,
  75: SoccerBotCountry.ITALY,
  76: SoccerBotCountry.JAMAICA,
  77: SoccerBotCountry.JAPAN,
  78: SoccerBotCountry.JORDAN,
  81: SoccerBotCountry.KAZAKHSTAN,
  82: SoccerBotCountry.KENYA,
  246: SoccerBotCountry.KIRIBATI,
  86: SoccerBotCountry.NORTH_KOREA,
  87: SoccerBotCountry.SOUTH_KOREA,
  244: SoccerBotCountry.KOSOVO,
  89: SoccerBotCountry.KUWAIT,
  90: SoccerBotCountry.KYRGYZSTAN,
  91: SoccerBotCountry.LAOS,
  92: SoccerBotCountry.LATVIA,
  94: SoccerBotCountry.LEBANON,
  93: SoccerBotCountry.LESOTHO,
  95: SoccerBotCountry.LIBERIA,
  96: SoccerBotCountry.LIBYA,
  97: SoccerBotCountry.LIECHTENSTEIN,
  98: SoccerBotCountry.LITHUANIA,
  99: SoccerBotCountry.LUXEMBOURG,
  219: SoccerBotCountry.MACAU,
  100: SoccerBotCountry.MACEDONIA,
  101: SoccerBotCountry.MADAGASCAR,
  102: SoccerBotCountry.MALAWI,
  103: SoccerBotCountry.MALAYSIA,
  104: SoccerBotCountry.MALDIVES,
  105: SoccerBotCountry.MALI,
  106: SoccerBotCountry.MALTA,
  268: SoccerBotCountry.NORTHERN_MARIANA_ISLANDS,
  207: SoccerBotCountry.MARTINIQUE,
  108: SoccerBotCountry.MAURITANIA,
  109: SoccerBotCountry.MAURITIUS,
  110: SoccerBotCountry.MEXICO,
  112: SoccerBotCountry.MOLDOVA,
  114: SoccerBotCountry.MONGOLIA,
  216: SoccerBotCountry.MONTENEGRO,
  235: SoccerBotCountry.MONTSERRAT,
  107: SoccerBotCountry.MOROCCO,
  115: SoccerBotCountry.MOZAMBIQUE,
  116: SoccerBotCountry.MYANMAR,
  117: SoccerBotCountry.NAMIBIA,
  118: SoccerBotCountry.NAURU,
  119: SoccerBotCountry.NEPAL,
  122: SoccerBotCountry.NETHERLANDS,
  236: SoccerBotCountry.NEW_CALEDONIA,
  120: SoccerBotCountry.NEW_ZEALAND,
  121: SoccerBotCountry.NICARAGUA,
  123: SoccerBotCountry.NIGER,
  124: SoccerBotCountry.NIGERIA,
  261: SoccerBotCountry.NIUE,
  192: SoccerBotCountry.NORTHERN_IRELAND,
  125: SoccerBotCountry.NORWAY,
  126: SoccerBotCountry.OMAN,
  242: SoccerBotCountry.TIMOR_LESTE,
  128: SoccerBotCountry.PAKISTAN,
  240: SoccerBotCountry.PALESTINE,
  129: SoccerBotCountry.PALAU,
  130: SoccerBotCountry.PANAMA,
  131: SoccerBotCountry.PAPUA_NEW_GUINEA,
  132: SoccerBotCountry.PARAGUAY,
  133: SoccerBotCountry.PERU,
  134: SoccerBotCountry.PHILIPPINES,
  135: SoccerBotCountry.POLAND,
  136: SoccerBotCountry.PORTUGAL,
  228: SoccerBotCountry.PUERTO_RICO,
  249: SoccerBotCountry.REUNION,
  140: SoccerBotCountry.ROMANIA,
  141: SoccerBotCountry.RUSSIA,
  139: SoccerBotCountry.RWANDA,
  143: SoccerBotCountry.SAMOA,
  144: SoccerBotCountry.SAN_MARINO,
  145: SoccerBotCountry.SAO_TOME_AND_PRINCIPE,
  146: SoccerBotCountry.SAUDI_ARABIA,
  190: SoccerBotCountry.SCOTLAND,
  149: SoccerBotCountry.SENEGAL,
  215: SoccerBotCountry.SERBIA,
  151: SoccerBotCountry.SEYCHELLES,
  152: SoccerBotCountry.SIERRA_LEONE,
  153: SoccerBotCountry.SINGAPORE,
  154: SoccerBotCountry.SLOVAKIA,
  155: SoccerBotCountry.SLOVENIA,
  69: SoccerBotCountry.SOLOMON_ISLANDS,
  159: SoccerBotCountry.SOUTH_AFRICA,
  262: SoccerBotCountry.SOUTH_SUDAN,
  157: SoccerBotCountry.SPAIN,
  158: SoccerBotCountry.SRI_LANKA,
  225: SoccerBotCountry.SAINT_KITS_AND_NEVIS,
  230: SoccerBotCountry.SAINT_LUCIA,
  224: SoccerBotCountry.SAINT_VINCENT_AND_THE_GRENADINES,
  160: SoccerBotCountry.SUDAN,
  161: SoccerBotCountry.SURINAME,
  147: SoccerBotCountry.SWEDEN,
  148: SoccerBotCountry.SWITZERLAND,
  163: SoccerBotCountry.SYRIA,
  237: SoccerBotCountry.TAHITI,
  165: SoccerBotCountry.TAJIKISTAN,
  166: SoccerBotCountry.TANZANIA,
  167: SoccerBotCountry.THAILAND,
  52: SoccerBotCountry.GAMBIA,
  168: SoccerBotCountry.TOGO,
  169: SoccerBotCountry.TONGA,
  170: SoccerBotCountry.TRINIDAD_AND_TOBAGO,
  173: SoccerBotCountry.TUNISIA,
  174: SoccerBotCountry.TURKEY,
  175: SoccerBotCountry.TURKMENISTAN,
  226: SoccerBotCountry.TURKS_AND_CAICOS_ISLANDS,
  247: SoccerBotCountry.TUVALU,
  176: SoccerBotCountry.UGANDA,
  177: SoccerBotCountry.UKRAINE,
  183: SoccerBotCountry.UNITED_ARAB_EMIRATES,
  184: SoccerBotCountry.UNITED_STATES,
  179: SoccerBotCountry.URUGUAY,
  180: SoccerBotCountry.UZBEKISTAN,
  181: SoccerBotCountry.VANUATU,
  182: SoccerBotCountry.VENEZUELA,
  185: SoccerBotCountry.VIETNAM,
  191: SoccerBotCountry.WALES,
  186: SoccerBotCountry.YEMEN,
  142: SoccerBotCountry.ZAMBIA,
  253: SoccerBotCountry.ZANZIBAR,
  187: SoccerBotCountry.ZIMBABWE
};

export const SOCCERWAY_COUNTRY: { [key: string]: SoccerBotCountry } = {
  'Afghanistan': SoccerBotCountry.AFGHANISTAN,
  'Albania': SoccerBotCountry.ALBANIA,
  'Algeria': SoccerBotCountry.ALGERIA,
  'Andorra': SoccerBotCountry.ANDORRA,
  'Angola': SoccerBotCountry.ANGUILLA,
  'Antigua_and_Barbuda': SoccerBotCountry.ANTIGUA_AND_BARBUDA,
  'Argentina': SoccerBotCountry.ARGENTINA,
  'Armenia': SoccerBotCountry.ARMENIA,
  'Aruba': SoccerBotCountry.ARUBA,
  'Australia': SoccerBotCountry.AUSTRALIA,
  'Austria': SoccerBotCountry.AUSTRIA,
  'Azerbaijan': SoccerBotCountry.AZERBAIJAN,
  'Bahrain': SoccerBotCountry.BAHRAIN,
  'Bangladesh': SoccerBotCountry.BANGLADESH,
  'Barbados': SoccerBotCountry.BARBADOS,
  'Belarus': SoccerBotCountry.BELARUS,
  'Belgium': SoccerBotCountry.BELGIUM,
  'Belize': SoccerBotCountry.BELIZE,
  'Benin': SoccerBotCountry.BENIN,
  'Bermuda': SoccerBotCountry.BERMUDA,
  'Bhutan': SoccerBotCountry.BHUTAN,
  'Bolivia': SoccerBotCountry.BOLIVIA,
  'Bosnia and Herzegovina': SoccerBotCountry.BOSNIA_AND_HERZEGOVINA,
  'Botswana': SoccerBotCountry.BOTSWANA,
  'Brazil': SoccerBotCountry.BRAZIL,
  'British Virgin Islands': SoccerBotCountry.BRITISH_VIRGIN_ISLANDS,
  'Brunei Darussalam': SoccerBotCountry.BRUNEI,
  'Bulgaria': SoccerBotCountry.BULGARIA,
  'Burkina Faso': SoccerBotCountry.BURKINA_FASO,
  'Burundi': SoccerBotCountry.BURUNDI,
  'Cambodia': SoccerBotCountry.CAMBODIA,
  'Cameroon': SoccerBotCountry.CAMEROON,
  'Canada': SoccerBotCountry.CANADA,
  'Cape Verde Islands': SoccerBotCountry.CAPE_VERDE,
  'Cayman Islands': SoccerBotCountry.CAYMAN_ISLANDS,
  'Chad': SoccerBotCountry.CHAD,
  'Chile': SoccerBotCountry.CHILE,
  'China PR': SoccerBotCountry.CHINA,
  'Chinese Taipei': SoccerBotCountry.CHINESE_TAIPEI,
  'Colombia': SoccerBotCountry.COLOMBIA,
  'Congo DR': SoccerBotCountry.DR_CONGO,
  'Congo': SoccerBotCountry.CONGO,
  'Cook Islands': SoccerBotCountry.COOK_ISLANDS,
  'Costa Rica': SoccerBotCountry.COSTA_RICA,
  'Croatia': SoccerBotCountry.CROATIA,
  'Cuba': SoccerBotCountry.CUBA,
  'Curaçao': SoccerBotCountry.CURACAO,
  'Cyprus': SoccerBotCountry.CYPRUS,
  'Czech Republic': SoccerBotCountry.CZECH_REPUBLIC,
  'Côte d\'Ivoire': SoccerBotCountry.IVORY_COAST,
  'Denmark': SoccerBotCountry.DENMARK,
  'Djibouti': SoccerBotCountry.DJIBOUTI,
  'Dominican Republic': SoccerBotCountry.DOMINICA,
  'Ecuador': SoccerBotCountry.ECUADOR,
  'Egypt': SoccerBotCountry.EGYPT,
  'El Salvador': SoccerBotCountry.EL_SALVADOR,
  'England': SoccerBotCountry.ENGLAND,
  'Estonia': SoccerBotCountry.ESTONIA,
  'Eswatini': SoccerBotCountry.ESWATINI,
  'Ethiopia': SoccerBotCountry.ETHIOPIA,
  'Faroe Islands': SoccerBotCountry.FAROE_ISLANDS,
  'Fiji': SoccerBotCountry.FIJI,
  'Finland': SoccerBotCountry.FINLAND,
  'France': SoccerBotCountry.FRANCE,
  'French Guiana': SoccerBotCountry.FRENCH_GUIANA,
  'Gabon': SoccerBotCountry.GABON,
  'Gambia': SoccerBotCountry.GAMBIA,
  'Georgia': SoccerBotCountry.GEORGIA,
  'Germany': SoccerBotCountry.GERMANY,
  'Ghana': SoccerBotCountry.GHANA,
  'Gibraltar': SoccerBotCountry.GIBRALTAR,
  'Greece': SoccerBotCountry.GREECE,
  'Grenada': SoccerBotCountry.GRENADA,
  'Guadeloupe': SoccerBotCountry.GUADELOUPE,
  'Guam': SoccerBotCountry.GUAM,
  'Guatemala': SoccerBotCountry.GUATEMALA,
  'Guinea': SoccerBotCountry.GUINEA,
  'Guyana': SoccerBotCountry.GUYANA,
  'Haiti': SoccerBotCountry.HAITI,
  'Honduras': SoccerBotCountry.HONDURAS,
  'Hong Kong': SoccerBotCountry.HONG_KONG,
  'Hungary': SoccerBotCountry.HUNGARY,
  'Iceland': SoccerBotCountry.ICELAND,
  'India': SoccerBotCountry.INDIA,
  'Indonesia': SoccerBotCountry.INDONESIA,
  'Iran': SoccerBotCountry.IRAN,
  'Iraq': SoccerBotCountry.IRAQ,
  'Israel': SoccerBotCountry.ISRAEL,
  'Italy': SoccerBotCountry.ITALY,
  'Jamaica': SoccerBotCountry.JAMAICA,
  'Japan': SoccerBotCountry.JAPAN,
  'Jordan': SoccerBotCountry.JORDAN,
  'Kazakhstan': SoccerBotCountry.KAZAKHSTAN,
  'Kenya': SoccerBotCountry.KENYA,
  'Korea Republic': SoccerBotCountry.SOUTH_KOREA,
  'Kosovo': SoccerBotCountry.KOSOVO,
  'Kuwait': SoccerBotCountry.KUWAIT,
  'Kyrgyz Republic': SoccerBotCountry.KYRGYZSTAN,
  'Laos': SoccerBotCountry.LAOS,
  'Latvia': SoccerBotCountry.LATVIA,
  'Lebanon': SoccerBotCountry.LEBANON,
  'Lesotho': SoccerBotCountry.LESOTHO,
  'Liberia': SoccerBotCountry.LIBERIA,
  'Libya': SoccerBotCountry.LIBYA,
  'Liechtenstein': SoccerBotCountry.LIECHTENSTEIN,
  'Lithuania': SoccerBotCountry.LITHUANIA,
  'Luxembourg': SoccerBotCountry.LUXEMBOURG,
  'Macao': SoccerBotCountry.MACAU,
  'Madagascar': SoccerBotCountry.MADAGASCAR,
  'Malawi': SoccerBotCountry.MALAWI,
  'Malaysia': SoccerBotCountry.MALAYSIA,
  'Maldives': SoccerBotCountry.MALDIVES,
  'Mali': SoccerBotCountry.MALI,
  'Malta': SoccerBotCountry.MALTA,
  'Martinique': SoccerBotCountry.MARTINIQUE,
  'Mauritania': SoccerBotCountry.MAURITANIA,
  'Mauritius': SoccerBotCountry.MAURITIUS,
  'Mexico': SoccerBotCountry.MEXICO,
  'Moldova': SoccerBotCountry.MOLDOVA,
  'Mongolia': SoccerBotCountry.MONGOLIA,
  'Montenegro': SoccerBotCountry.MONTENEGRO,
  'Morocco': SoccerBotCountry.MOROCCO,
  'Mozambique': SoccerBotCountry.MOZAMBIQUE,
  'Myanmar': SoccerBotCountry.MYANMAR,
  'Nepal': SoccerBotCountry.NEPAL,
  'Netherlands': SoccerBotCountry.NETHERLANDS,
  'New Caledonia': SoccerBotCountry.NEW_CALEDONIA,
  'New Zealand': SoccerBotCountry.NEW_ZEALAND,
  'Nicaragua': SoccerBotCountry.NICARAGUA,
  'Niger': SoccerBotCountry.NIGER,
  'Nigeria': SoccerBotCountry.NIGERIA,
  'North Macedonia': SoccerBotCountry.MACEDONIA,
  'Northern Ireland': SoccerBotCountry.NORTHERN_IRELAND,
  'Norway': SoccerBotCountry.NORWAY,
  'Oman': SoccerBotCountry.OMAN,
  'Pakistan': SoccerBotCountry.PAKISTAN,
  'Palestine': SoccerBotCountry.PALESTINE,
  'Panama': SoccerBotCountry.PANAMA,
  'Papua New Guinea': SoccerBotCountry.PAPUA_NEW_GUINEA,
  'Paraguay': SoccerBotCountry.PARAGUAY,
  'Peru': SoccerBotCountry.PERU,
  'Philippines': SoccerBotCountry.PHILIPPINES,
  'Poland': SoccerBotCountry.POLAND,
  'Portugal': SoccerBotCountry.PORTUGAL,
  'Puerto Rico': SoccerBotCountry.PUERTO_RICO,
  'Qatar': SoccerBotCountry.QATAR,
  'Republic of Ireland': SoccerBotCountry.IRELAND,
  'Romania': SoccerBotCountry.ROMANIA,
  'Russia': SoccerBotCountry.RUSSIA,
  'Rwanda': SoccerBotCountry.RWANDA,
  'Réunion': SoccerBotCountry.REUNION,
  'Samoa': SoccerBotCountry.SAMOA,
  'San Marino': SoccerBotCountry.SAN_MARINO,
  'Saudi Arabia': SoccerBotCountry.SAUDI_ARABIA,
  'Scotland': SoccerBotCountry.SCOTLAND,
  'Senegal': SoccerBotCountry.SENEGAL,
  'Serbia': SoccerBotCountry.SERBIA,
  'Sierra Leone': SoccerBotCountry.SIERRA_LEONE,
  'Singapore': SoccerBotCountry.SINGAPORE,
  'Slovakia': SoccerBotCountry.SLOVAKIA,
  'Slovenia': SoccerBotCountry.SLOVENIA,
  'Solomon Islands': SoccerBotCountry.SOLOMON_ISLANDS,
  'Somalia': SoccerBotCountry.SOMALIA,
  'South Africa': SoccerBotCountry.SOUTH_AFRICA,
  'Spain': SoccerBotCountry.SPAIN,
  'Sri Lanka': SoccerBotCountry.SRI_LANKA,
  'St. Kitts and Nevis': SoccerBotCountry.SAINT_KITS_AND_NEVIS,
  'Sudan': SoccerBotCountry.SUDAN,
  'Suriname': SoccerBotCountry.SURINAME,
  'Sweden': SoccerBotCountry.SWEDEN,
  'Switzerland': SoccerBotCountry.SWITZERLAND,
  'Syria': SoccerBotCountry.SYRIA,
  'São Tomé e Príncipe': SoccerBotCountry.SAO_TOME_AND_PRINCIPE,
  'Tahiti': SoccerBotCountry.TAHITI,
  'Tajikistan': SoccerBotCountry.TAJIKISTAN,
  'Tanzania': SoccerBotCountry.TANZANIA,
  'Thailandt': SoccerBotCountry.THAILAND,
  'Togo': SoccerBotCountry.TOGO,
  'Trinidad and Tobago': SoccerBotCountry.TRINIDAD_AND_TOBAGO,
  'Tunisia': SoccerBotCountry.TUNISIA,
  'Turkey': SoccerBotCountry.TURKEY,
  'Turkmenistan': SoccerBotCountry.TURKMENISTAN,
  'Turks and Caicos Islands': SoccerBotCountry.TURKS_AND_CAICOS_ISLANDS,
  'USA': SoccerBotCountry.UNITED_STATES,
  'Uganda': SoccerBotCountry.UGANDA,
  'Ukraine': SoccerBotCountry.UKRAINE,
  'United Arab Emirates': SoccerBotCountry.UNITED_ARAB_EMIRATES,
  'Uruguay': SoccerBotCountry.URUGUAY,
  'Uzbekistan': SoccerBotCountry.UZBEKISTAN,
  'Venezuela': SoccerBotCountry.VENEZUELA,
  'Vietnam': SoccerBotCountry.VIETNAM,
  'Wales': SoccerBotCountry.WALES,
  'Yemen': SoccerBotCountry.YEMEN,
  'Zambia': SoccerBotCountry.ZAMBIA,
  'Zimbabwe': SoccerBotCountry.ZIMBABWE
};
