export enum SoccerBotCountryUefa {
  ALBANIA = 'ALBANIA',
  ANDORRA = 'ANDORRA',
  ARMENIA = 'ARMENIA',
  AUSTRIA = 'AUSTRIA',
  AZERBAIJAN = 'AZERBAIJAN',
  BELARUS = 'BELARUS',
  BELGIUM = 'BELGIUM',
  BOSNIA_AND_HERZEGOVINA = 'BOSNIA_AND_HERZEGOVINA',
  BULGARIA = 'BULGARIA',
  CROATIA = 'CROATIA',
  CYPRUS = 'CYPRUS',
  CZECH_REPUBLIC = 'CZECH_REPUBLIC',
  DENMARK = 'DENMARK',
  ENGLAND = 'ENGLAND',
  ESTONIA = 'ESTONIA',
  FAROE_ISLANDS = 'FAROE_ISLANDS',
  FINLAND = 'FINLAND',
  FRANCE = 'FRANCE',
  GEORGIA = 'GEORGIA',
  GERMANY = 'GERMANY',
  GIBRALTAR = 'GIBRALTAR',
  GREECE = 'GREECE',
  HUNGARY = 'HUNGARY',
  ICELAND = 'ICELAND',
  IRELAND = 'IRELAND',
  ISRAEL = 'ISRAEL',
  ITALY = 'ITALY',
  KAZAKHSTAN = 'KAZAKHSTAN',
  KOSOVO = 'KOSOVO',
  LATVIA = 'LATVIA',
  LIECHTENSTEIN = 'LIECHTENSTEIN',
  LITHUANIA = 'LITHUANIA',
  LUXEMBOURG = 'LUXEMBOURG',
  MACEDONIA = 'MACEDONIA',
  MALTA = 'MALTA',
  MOLDOVA = 'MOLDOVA',
  MONTENEGRO = 'MONTENEGRO',
  NETHERLANDS = 'NETHERLANDS',
  NORTHERN_IRELAND = 'NORTHERN_IRELAND',
  NORWAY = 'NORWAY',
  POLAND = 'POLAND',
  PORTUGAL = 'PORTUGAL',
  ROMANIA = 'ROMANIA',
  RUSSIA = 'RUSSIA',
  SAN_MARINO = 'SAN_MARINO',
  SCOTLAND = 'SCOTLAND',
  SERBIA = 'SERBIA',
  SLOVAKIA = 'SLOVAKIA',
  SLOVENIA = 'SLOVENIA',
  SPAIN = 'SPAIN',
  SWEDEN = 'SWEDEN',
  SWITZERLAND = 'SWITZERLAND',
  TURKEY = 'TURKEY',
  UKRAINE = 'UKRAINE',
  WALES = 'WALES'
}

export enum SoccerBotCountryCaf {
  ALGERIA = 'ALGERIA',
  ANGOLA = 'ANGOLA',
  BENIN = 'BENIN',
  BOTSWANA = 'BOTSWANA',
  BURKINA_FASO = 'BURKINA_FASO',
  BURUNDI = 'BURUNDI',
  CAMEROON = 'CAMEROON',
  CAPE_VERDE = 'CAPE_VERDE',
  CENTRAL_AFRICAN_REPUBLIC = 'CENTRAL_AFRICAN_REPUBLIC',
  COMOROS = 'COMOROS',
  CONGO = 'CONGO',
  DJIBOUTI = 'DJIBOUTI',
  DR_CONGO = 'DR_CONGO',
  EGYPT = 'EGYPT',
  EQUATORIAL_GUINEA = 'EQUATORIAL_GUINEA',
  ERITREA = 'ERITREA',
  ESWATINI = 'ESWATINI',
  ETHIOPIA = 'ETHIOPIA',
  GABON = 'GABON',
  GAMBIA = 'GAMBIA',
  GHANA = 'GHANA',
  GUINEA = 'GUINEA',
  GUINEA_BISSAU = 'GUINEA_BISSAU',
  CHAD = 'CHAD',
  IVORY_COAST = 'IVORY_COAST',
  KENYA = 'KENYA',
  LESOTHO = 'LESOTHO',
  LIBERIA = 'LIBERIA',
  LIBYA = 'LIBYA',
  MADAGASCAR = 'MADAGASCAR',
  MALAWI = 'MALAWI',
  MALI = 'MALI',
  MAURITANIA = 'MAURITANIA',
  MAURITIUS = 'MAURITIUS',
  MOROCCO = 'MOROCCO',
  MOZAMBIQUE = 'MOZAMBIQUE',
  NAMIBIA = 'NAMIBIA',
  NIGER = 'NIGER',
  NIGERIA = 'NIGERIA',
  REUNION = 'REUNION',
  RWANDA = 'RWANDA',
  SAO_TOME_AND_PRINCIPE = 'SAO_TOME_AND_PRINCIPE',
  SENEGAL = 'SENEGAL',
  SEYCHELLES = 'SEYCHELLES',
  SIERRA_LEONE = 'SIERRA_LEONE',
  SOMALIA = 'SOMALIA',
  SOUTH_AFRICA = 'SOUTH_AFRICA',
  SOUTH_SUDAN = 'SOUTH_SUDAN',
  SUDAN = 'SUDAN',
  TANZANIA = 'TANZANIA',
  TOGO = 'TOGO',
  TUNISIA = 'TUNISIA',
  UGANDA = 'UGANDA',
  ZAMBIA = 'ZAMBIA',
  ZIMBABWE = 'ZIMBABWE'
}

export enum SoccerBotCountryAfc {
  AFGHANISTAN = 'AFGHANISTAN',
  AUSTRALIA = 'AUSTRALIA',
  BAHRAIN = 'BAHRAIN',
  BANGLADESH = 'BANGLADESH',
  BHUTAN = 'BHUTAN',
  BRUNEI = 'BRUNEI',
  CAMBODIA = 'CAMBODIA',
  GUAM = 'GUAM',
  HONG_KONG = 'HONG_KONG',
  CHINA = 'CHINA',
  CHINESE_TAIPEI = 'CHINESE_TAIPEI',
  INDIA = 'INDIA',
  INDONESIA = 'INDONESIA',
  IRAN = 'IRAN',
  IRAQ = 'IRAQ',
  JAPAN = 'JAPAN',
  JORDAN = 'JORDAN',
  KUWAIT = 'KUWAIT',
  KYRGYZSTAN = 'KYRGYZSTAN',
  LAOS = 'LAOS',
  LEBANON = 'LEBANON',
  MACAU = 'MACAU',
  MALAYSIA = 'MALAYSIA',
  MALDIVES = 'MALDIVES',
  MONGOLIA = 'MONGOLIA',
  MYANMAR = 'MYANMAR',
  NEPAL = 'NEPAL',
  NORTH_KOREA = 'NORTH_KOREA',
  NORTHERN_MARIANA_ISLANDS = 'NORTHERN_MARIANA_ISLANDS',
  OMAN = 'OMAN',
  PAKISTAN = 'PAKISTAN',
  PALESTINE = 'PALESTINE',
  PHILIPPINES = 'PHILIPPINES',
  QATAR = 'QATAR',
  SAUDI_ARABIA = 'SAUDI_ARABIA',
  SINGAPORE = 'SINGAPORE',
  SOUTH_KOREA = 'SOUTH_KOREA',
  SRI_LANKA = 'SRI_LANKA',
  SYRIA = 'SYRIA',
  TAJIKISTAN = 'TAJIKISTAN',
  THAILAND = 'THAILAND',
  TIMOR_LESTE = 'TIMOR_LESTE',
  TURKMENISTAN = 'TURKMENISTAN',
  UNITED_ARAB_EMIRATES = 'UNITED_ARAB_EMIRATES',
  UZBEKISTAN = 'UZBEKISTAN',
  VIETNAM = 'VIETNAM',
  YEMEN = 'YEMEN',
  ZANZIBAR = 'ZANZIBAR'
}

export enum SoccerBotCountryOfc {
  AMERICAN_SAMOA = 'AMERICAN_SAMOA',
  COOK_ISLANDS = 'COOK_ISLANDS',
  FIJI = 'FIJI',
  KIRIBATI = 'KIRIBATI',
  MICRONESIA = 'MICRONESIA',
  NAURU = 'NAURU',
  NEW_CALEDONIA = 'NEW_CALEDONIA',
  NEW_ZEALAND = 'NEW_ZEALAND',
  NIUE = 'NIUE',
  PAPUA_NEW_GUINEA = 'PAPUA_NEW_GUINEA',
  PALAU = 'PALAU',
  SAMOA = 'SAMOA',
  SOLOMON_ISLANDS = 'SOLOMON_ISLANDS',
  TAHITI = 'TAHITI',
  TONGA = 'TONGA',
  TUVALU = 'TUVALU',
  VANUATU = 'VANUATU'
}

export enum SoccerBotCountryConmebol {
  ARGENTINA = 'ARGENTINA',
  BOLIVIA = 'BOLIVIA',
  BRAZIL = 'BRAZIL',
  COLOMBIA = 'COLOMBIA',
  ECUADOR = 'ECUADOR',
  CHILE = 'CHILE',
  PARAGUAY = 'PARAGUAY',
  PERU = 'PERU',
  URUGUAY = 'URUGUAY',
  VENEZUELA = 'VENEZUELA'
}

export enum SoccerBotCountryConcacaf {
  ANGUILLA = 'ANGUILLA',
  ANTIGUA_AND_BARBUDA = 'ANTIGUA_AND_BARBUDA',
  ARUBA = 'ARUBA',
  BAHAMAS = 'BAHAMAS',
  BARBADOS = 'BARBADOS',
  BELIZE = 'BELIZE',
  BERMUDA = 'BERMUDA',
  BONAIRE = 'BONAIRE',
  BRITISH_VIRGIN_ISLANDS = 'BRITISH_VIRGIN_ISLANDS',
  CANADA = 'CANADA',
  CAYMAN_ISLANDS = 'CAYMAN_ISLANDS',
  COSTA_RICA = 'COSTA_RICA',
  CUBA = 'CUBA',
  CURACAO = 'CURACAO',
  DOMINICA = 'DOMINICA',
  DOMINICAN_REPUBLIC = 'DOMINICAN_REPUBLIC',
  EL_SALVADOR = 'EL_SALVADOR',
  FRENCH_GUIANA = 'FRENCH_GUIANA',
  GRENADA = 'GRENADA',
  GUADELOUPE = 'GUADELOUPE',
  GUATEMALA = 'GUATEMALA',
  GUYANA = 'GUYANA',
  HAITI = 'HAITI',
  HONDURAS = 'HONDURAS',
  JAMAICA = 'JAMAICA',
  MARTINIQUE = 'MARTINIQUE',
  MEXICO = 'MEXICO',
  MONTSERRAT = 'MONTSERRAT',
  NICARAGUA = 'NICARAGUA',
  PANAMA = 'PANAMA',
  PUERTO_RICO = 'PUERTO_RICO',
  SAINT_KITS_AND_NEVIS = 'SAINT_KITS_AND_NEVIS',
  SAINT_LUCIA = 'SAINT_LUCIA',
  SAINT_MARTIN = 'SAINT_MARTIN',
  SAINT_VINCENT_AND_THE_GRENADINES = 'SAINT_VINCENT_AND_THE_GRENADINES',
  SINT_MAARTEN = 'SINT_MAARTEN',
  SURINAME = 'SURINAME',
  TRINIDAD_AND_TOBAGO = 'TRINIDAD_AND_TOBAGO',
  TURKS_AND_CAICOS_ISLANDS = 'TURKS_AND_CAICOS_ISLANDS',
  UNITED_STATES = 'UNITED_STATES',
  US_VIRGIN_ISLANDS = 'US_VIRGIN_ISLANDS'
}

export const SoccerBotCountry = {
  ...SoccerBotCountryUefa,
  ...SoccerBotCountryCaf,
  ...SoccerBotCountryAfc,
  ...SoccerBotCountryOfc,
  ...SoccerBotCountryConmebol,
  ...SoccerBotCountryConcacaf
};

export type SoccerBotCountry =
  | SoccerBotCountryUefa
  | SoccerBotCountryCaf
  | SoccerBotCountryAfc
  | SoccerBotCountryOfc
  | SoccerBotCountryConmebol
  | SoccerBotCountryConcacaf;

export enum SoccerBotFoot {
  RIGHT = 'RIGHT',
  LEFT = 'LEFT'
}

export enum SoccerBotPositionGroup {
  GOALKEEPER = 'GOALKEEPER',
  DEFENDER = 'DEFENDER',
  MIDFIELDER = 'MIDFIELDER',
  ATTACKER = 'ATTACKER'
}

export interface SoccerBotResponse<T> {
  ok: boolean;
  data?: T;
  errors?: any;
}

export interface SoccerBotTeam {
  id: string;
  name: string;
}

export interface SoccerBotPlayer {
  id?: string;
  name?: string;
  firstName?: string;
  lastName?: string;
  jerseyNumber?: number;
  position?: SoccerBotPositionGroup;
  birthdate?: string;
  height?: number;
  weight?: number;
  foot?: SoccerBotFoot;
  joined?: string;
  contractExpires?: string;
  marketValue?: number;
  country?: SoccerBotCountry;
  minutesPlayed?: number;
}

export enum SoccerBotProvider {
  TRANSFERMARKT = 'TRANSFERMARKT',
  SOCCERWAY = 'SOCCERWAY',
  FOTBALUNAS = 'FOTBALUNAS',
  EUROFOTBAL = 'EUROFOTBAL',
  SPORTNET = 'SPORTNET'
}
