name: Install Dependencies
description: Install dependencies from the frozen Yarn lockfile
runs:
  using: composite
  steps:
    - name: Install
      run: yarn install --frozen-lockfile
      shell: bash
