name: 🐛 Test feature branch
'on': pull_request

permissions:
  contents: read
  pull-requests: write

jobs:
  install-and-test:
    name: 🛠️ Install & Test
    runs-on: ubuntu-latest

    steps:
      - name: 🗜️ Checkout
        uses: actions/checkout@v7

      - name: 🗜️ Setup node version
        uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
          cache: yarn
          registry-url: 'https://registry.npmjs.org'

      - name: 🛠️ Install
        uses: ./.github/actions/cached-deps

      - name: 📦 Build
        run: yarn build

      - name: 🧹 Run lint
        run: yarn lint

      - name: 🧪 Run tests
        run: yarn test --coverage --run

      - name: 🧪 Create coverage report
        uses: davelosert/vitest-coverage-report-action@v2
        if: always()
        with:
          vite-config-path: ./vitest.config.ts
          json-summary-path: ./coverage/coverage-summary.json
          json-final-path: ./coverage/coverage-final.json

      # - name: ⬆️ Upload coverage reports
      #   uses: codecov/codecov-action@v7
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
      #     fail_ci_if_error: true
      #     verbose: true
      #     dry_run: true
